In [2]:
import numpy as np
import math
from __future__ import division

In [3]:
n = 5
A = np.matrix([[np.random.randint(30)*np.random.choice([-1,1]) for _ in range(n+1)] for _ in range(n)]).astype(float)
B = A.copy()

In [4]:
print(B)

[[-13.  -1.  22.  28. -25. -24.]
 [-25. -22.  16. -21.  13. -22.]
 [ 12.  -3.  -4.  11. -18.   5.]
 [-15.  29.  28.  -2. -13. -17.]
 [-14.  26. -28. -14. -27. -15.]]


In [5]:
for j in range(n-1):
    k = 1
    while A[j,j] == 0:
        A[[j,j+k]] = A[[j+k,j]]
        k += 1
    for i in range(j+1,n):    
        A[i] = A[i]-A[j]*1/(A[j,j])*A[i,j]

In [6]:
print(A)

[[ -13.           -1.           22.           28.          -25.
   -24.        ]
 [   0.          -20.07692308  -26.30769231  -74.84615385   61.07692308
    24.15384615]
 [   0.            0.           21.44827586   51.47126437  -53.01149425
   -21.87356322]
 [   0.            0.            0.          -58.1764916    16.38513755
     9.34119328]
 [   0.            0.            0.            0.         -115.10678228
   -35.18725589]]


In [7]:
X = np.matrix([0 for x in range(n)]).astype(float)
X[0,n-1] = A[n-1,n]/A[n-1,n-1]
for i in range(n-1):
    X[0,n-i-2] = (A[n-i-2,n] -sum([A[n-i-2,j+1]*X[0,j+1] for j in range(n-i-2,n-1)]))/A[n-i-2,n-i-2]
print(X)    

[[ 0.94410615  0.11664101 -0.08556916 -0.07446965  0.30569229]]


In [8]:
B[:,range(n)]*X.T

matrix([[-24.],
        [-22.],
        [  5.],
        [-17.],
        [-15.]])

In [9]:
B[:,[n]]

matrix([[-24.],
        [-22.],
        [  5.],
        [-17.],
        [-15.]])