In [122]:
from __future__ import division
from math import cos,sin,sqrt

In [95]:
import numpy as np

In [111]:
f = lambda x:np.array((1/2*cos(x[0])-1/2*sin(x[1]),
                       1/2*sin(x[0])+1/2*cos(x[1])))

In [124]:
x = np.array((0,1))
q = 1/sqrt(2)
while np.linalg.norm(x-f(x))>0.0000001:
    print(x,q/(1-q)*np.linalg.norm(x-f(x)))
    x = f(x)

(array([0, 1]), 1.7723718333814404)
(array([0.07926451, 0.27015115]), 0.9186521815993188)
(array([0.36499155, 0.52145605]), 0.41683068637390663)
(array([0.21799179, 0.61201809]), 0.23217035072994424)
(array([0.20090666, 0.51737981]), 0.10875521998482228)
(array([0.24264073, 0.53433798]), 0.048363704175341096)
(array([0.23071774, 0.5504364 ]), 0.027442626588513725)
(array([0.22522165, 0.54048632]), 0.011769498499085394)
(array([0.23009579, 0.54039048]), 0.00592022689505649)
(array([0.22958684, 0.54278932]), 0.0031390396571138123)
(array([0.22861704, 0.54192324]), 0.0013073302720694186)
(array([0.22909806, 0.54167453]), 0.000731170658295773)
(array([0.22915005, 0.54197289]), 0.00034604645588840366)
(array([0.22901633, 0.54192127]), 0.000154095985009347)
(array([0.22905362, 0.54186947]), 8.757372835008464e-05)
(array([0.22907158, 0.54190099]), 3.7546549925299684e-05)
(array([0.22905604, 0.54190161]), 1.90003102616375e-05)
(array([0.22905754, 0.54189388]), 1.0032536007866847e-05)
(array([0