In [51]:
from __future__ import division
import numpy as np
import math
from math import sqrt

In [2]:
A = np.matrix([[5,0,-2],[-4,8,2],[0,5,9]]).astype(float)
A

matrix([[ 5.,  0., -2.],
        [-4.,  8.,  2.],
        [ 0.,  5.,  9.]])

In [58]:
y = np.matrix([-1,18,37]).astype(float).T
print(y)

[[-1.]
 [18.]
 [37.]]


In [174]:
def Jacobi(A,y,error):
    n = len(A)
    def q_uno(A):
        return(max(sum(abs(A[k,j]/A[j,j]) for k in range(n) if k != j) 
        for j in range(n)))
    def q_inf(A):
        return(max(sum(abs(A[j,k]/A[j,j]) for k in range(n) if k != j) 
        for j in range(n)))
    def q_dos(A):
        return(sqrt(sum(sum(abs(A[j,k]/A[j,j])**2 for k in range(n) if k != j) 
        for j in range(n))))
    if (q_uno(A)<1) or (q_inf(A)<1) or (q_dos(A)<1):
        x = np.matrix([0 for _ in range(n)]).astype(float).T
        while (np.linalg.norm(A*x-y)>error):
            for j in range(n):
                x[j,0] = -sum(A[j,k]/A[j,j]*x[k,0] for k in range(n) if j != k)+y[j,0]/A[j,j]
        return(x)
    else:
        print("El sistema no cumple las hipótesis")

In [176]:
Jacobi(A,y,0.00000001)

matrix([[1.],
        [2.],
        [3.]])

In [196]:
B = np.matrix([[np.random.randint(50) for j in range(5)] for i in range(5)]).astype(float)
w = np.matrix([np.random.randint(50) for j in range(5)]).astype(float).T
print(B)
print(w)

[[ 7. 15. 29. 15. 21.]
 [36. 29. 16. 27. 47.]
 [15.  0.  6. 45.  5.]
 [38.  6. 30. 26. 14.]
 [11. 27. 35.  6. 30.]]
[[17.]
 [17.]
 [ 6.]
 [16.]
 [16.]]


In [197]:
Jacobi(B,w,0.0001)

El sistema no cumple las hipótesis
