In [1]:
import numpy as np
import math

In [57]:
n = 6
A = np.array([[np.random.randint(10)*np.random.choice([-1,1]) for x in range(n)] for y in range(n)]).astype(float)
A = A.astype(float)
A1 = A.copy()
print(A)

[[ 6.  3.  7.  6. -5.  0.]
 [-7. -4. -1.  6. -1. -4.]
 [-6.  7.  3.  6. -6.  8.]
 [-3.  6. -8.  9. -5.  4.]
 [-9. -2. -8.  0. -7.  8.]
 [ 3. -9. -8. -8. -2. -1.]]


In [60]:
d = np.diagflat(np.diag(A))
U = (np.tril(A.T).T) - d
L = (np.tril(A)) - d