In [3]:
import numpy as np
import math

In [646]:
n = 6
A = np.matrix([[np.random.randint(10)*np.random.choice([-1,1]) for x in range(n+1)] for y in range(n)]).astype(float)
A = A.astype(float)
A1 = A.copy()
print(A)

[[ 8.  5.  5. -1.  6.  4.  3.]
 [-7. -3.  7. -3.  1. -2.  3.]
 [ 3.  3.  2. -7. -1. -5.  5.]
 [ 8. -9. -5.  4.  1. -4.  9.]
 [-5.  5. -6.  0.  1. -3.  3.]
 [ 1.  1. -4. -9. -6. -7.  5.]]


In [647]:
for i in range(1,n):
    if A[i-1,i-1] == 0:
        A[[i-1,i]] = A[[i,i-1]]
    for j in range(i,n):
        A[j] = A[j]-(A[j,i-1]/A[i-1,i-1])*A[i-1]
print(A)

[[  8.           5.           5.          -1.           6.
    4.           3.        ]
 [  0.           1.375       11.375       -3.875        6.25
    1.5          5.625     ]
 [  0.           0.          -9.18181818  -3.45454545  -8.36363636
   -7.72727273  -0.72727273]
 [  0.           0.           0.         -74.26732673 -37.75247525
  -81.78217822  54.89108911]
 [  0.           0.           0.           0.           6.93627516
   -3.94187442  13.14064791]
 [  0.           0.           0.           0.           0.
    4.61592573  -1.97370697]]


In [648]:
X = np.matrix([0 for x in range(n)]).astype(float)
X[0,n-1] = A[n-1,n]/A[n-1,n-1]
for i in range(n-1):
    X[0,n-i-2] = (A[n-i-2,n]-sum([A[n-i-2,j+1]*X[0,j+1] for j in range(n-i-2,n-1)]))/A[n-i-2,n-i-2]

In [649]:
X

matrix([[ 0.05856047, -0.70647313, -0.64848727, -1.10775227,  1.65148525,
         -0.42758638]])

In [650]:
A1[:,[k for k in range(n)]]*X.T

matrix([[3.],
        [3.],
        [5.],
        [9.],
        [3.],
        [5.]])